#pragma once

#include "Board.h"
#include "Rules.h"

// Generated by tools/board-data/generate.py. Do not edit by hand.
extern const BoardPoint ClassicBoardPoints[] PROGMEM;
extern const uint16_t ClassicMills[] PROGMEM;
extern const uint8_t ClassicAdjacencyOffsets[] PROGMEM;
extern const uint8_t ClassicAdjacency[] PROGMEM;
extern const BoardDefinition ClassicBoardDefinition;
extern const BoardPoint FlowerBoardPoints[] PROGMEM;
extern const uint16_t FlowerMills[] PROGMEM;
extern const uint8_t FlowerAdjacencyOffsets[] PROGMEM;
extern const uint8_t FlowerAdjacency[] PROGMEM;
extern const BoardDefinition FlowerBoardDefinition;
extern const BoardPoint LongMorrisBoardPoints[] PROGMEM;
extern const uint16_t LongMorrisMills[] PROGMEM;
extern const uint8_t LongMorrisAdjacencyOffsets[] PROGMEM;
extern const uint8_t LongMorrisAdjacency[] PROGMEM;
extern const BoardDefinition LongMorrisBoardDefinition;
extern const BoardPoint SixMenBoardPoints[] PROGMEM;
extern const uint16_t SixMenMills[] PROGMEM;
extern const uint8_t SixMenAdjacencyOffsets[] PROGMEM;
extern const uint8_t SixMenAdjacency[] PROGMEM;
extern const BoardDefinition SixMenBoardDefinition;
extern const BoardPoint ThreeMenBoardPoints[] PROGMEM;
extern const uint16_t ThreeMenMills[] PROGMEM;
extern const uint8_t ThreeMenAdjacencyOffsets[] PROGMEM;
extern const uint8_t ThreeMenAdjacency[] PROGMEM;
extern const BoardDefinition ThreeMenBoardDefinition;
extern const RuleSet ClassicRuleSet;
extern const RuleSet FlowerRuleSet;
extern const RuleSet LongMorrisRuleSet;
extern const RuleSet SixMenRuleSet;
extern const RuleSet ThreeMenRuleSet;

constexpr uint8_t MORRIS_BOARD_PROFILE_COUNT = 5;
extern const BoardDefinition *const MorrisBoardProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM;
extern const RuleSet *const MorrisRuleProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM;
