#include "GeneratedBoards.h"

// Generated by tools/board-data/generate.py. Do not edit by hand.

const BoardPoint ClassicBoardPoints[] PROGMEM = {
  {4, 4},
  {32, 4},
  {60, 4},
  {12, 12},
  {32, 12},
  {52, 12},
  {20, 20},
  {32, 20},
  {44, 20},
  {4, 32},
  {12, 32},
  {20, 32},
  {44, 32},
  {52, 32},
  {60, 32},
  {20, 44},
  {32, 44},
  {44, 44},
  {12, 52},
  {32, 52},
  {52, 52},
  {4, 60},
  {32, 60},
  {60, 60},
};

const uint16_t ClassicMills[] PROGMEM = {
  2080,
  5251,
  8422,
  11593,
  14764,
  17935,
  21106,
  24277,
  21792,
  18755,
  15718,
  7297,
  23152,
  17800,
  20901,
  24002,
};

const uint8_t ClassicAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 9, 13, 15, 17, 20, 22, 25, 29, 32, 35, 39, 42, 44, 47, 49, 51, 55, 57, 59, 62, 64,
};

const uint8_t ClassicAdjacency[] PROGMEM = {
  1, 9,
  0, 2, 4,
  1, 14,
  4, 10,
  1, 3, 5, 7,
  4, 13,
  7, 11,
  4, 6, 8,
  7, 12,
  0, 10, 21,
  3, 9, 11, 18,
  6, 10, 15,
  8, 13, 17,
  5, 12, 14, 20,
  2, 13, 23,
  11, 16,
  15, 17, 19,
  12, 16,
  10, 19,
  16, 18, 20, 22,
  13, 19,
  9, 22,
  19, 21, 23,
  14, 22,
};

const BoardDefinition ClassicBoardDefinition = {
  "classic-nine",
  "CLASSIC 9",
  24,
  16,
  ClassicBoardPoints,
  ClassicMills,
  ClassicAdjacencyOffsets,
  ClassicAdjacency,
};

const RuleSet ClassicRuleSet = {
  "classic-nine",
  9,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint FlowerBoardPoints[] PROGMEM = {
  {4, 23},
  {4, 35},
  {10, 29},
  {22, 41},
  {29, 35},
  {29, 54},
  {23, 60},
  {35, 60},
  {41, 42},
  {35, 35},
  {54, 35},
  {60, 41},
  {60, 29},
  {42, 23},
  {35, 29},
  {35, 10},
  {41, 4},
  {29, 4},
  {23, 22},
  {29, 29},
};

const uint16_t FlowerMills[] PROGMEM = {
  3136,
  19589,
  8358,
  10532,
  13643,
  15817,
  16882,
  14946,
};

const uint8_t FlowerAdjacencyOffsets[] PROGMEM = {
  0, 2, 4, 8, 10, 14, 18, 20, 22, 24, 28, 32, 34, 36, 38, 42, 46, 48, 50, 52, 56,
};

const uint8_t FlowerAdjacency[] PROGMEM = {
  1, 2,
  0, 2,
  0, 1, 3, 19,
  2, 4,
  3, 5, 9, 19,
  4, 6, 7, 8,
  5, 7,
  5, 6,
  5, 9,
  4, 8, 10, 14,
  9, 11, 12, 13,
  10, 12,
  10, 11,
  10, 14,
  9, 13, 15, 19,
  14, 16, 17, 18,
  15, 17,
  15, 16,
  15, 19,
  2, 4, 14, 18,
};

const BoardDefinition FlowerBoardDefinition = {
  "flower",
  "FLOWER",
  20,
  8,
  FlowerBoardPoints,
  FlowerMills,
  FlowerAdjacencyOffsets,
  FlowerAdjacency,
};

const RuleSet FlowerRuleSet = {
  "flower",
  7,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint SixMenBoardPoints[] PROGMEM = {
  {4, 4},
  {32, 4},
  {60, 4},
  {60, 32},
  {60, 60},
  {32, 60},
  {4, 60},
  {4, 32},
  {18, 18},
  {32, 18},
  {46, 18},
  {46, 32},
  {46, 46},
  {32, 46},
  {18, 46},
  {18, 32},
};

const uint16_t SixMenMills[] PROGMEM = {
  2080,
  4194,
  6308,
  230,
  10536,
  12650,
  14764,
  8686,
};

const uint8_t SixMenAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 35, 37, 40,
};

const uint8_t SixMenAdjacency[] PROGMEM = {
  1, 7,
  0, 2, 9,
  1, 3,
  2, 4, 11,
  3, 5,
  4, 6, 13,
  5, 7,
  0, 6, 15,
  9, 15,
  1, 8, 10,
  9, 11,
  3, 10, 12,
  11, 13,
  5, 12, 14,
  13, 15,
  7, 8, 14,
};

const BoardDefinition SixMenBoardDefinition = {
  "six-men",
  "SIX MEN",
  16,
  8,
  SixMenBoardPoints,
  SixMenMills,
  SixMenAdjacencyOffsets,
  SixMenAdjacency,
};

const RuleSet SixMenRuleSet = {
  "six-men",
  6,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint ThreeMenBoardPoints[] PROGMEM = {
  {12, 12},
  {32, 12},
  {52, 12},
  {12, 32},
  {32, 32},
  {52, 32},
  {12, 52},
  {32, 52},
  {52, 52},
};

const uint16_t ThreeMenMills[] PROGMEM = {
  2080,
  5251,
  8422,
  6240,
  7297,
  8354,
  8320,
  6274,
};

const uint8_t ThreeMenAdjacencyOffsets[] PROGMEM = {
  0, 3, 6, 9, 12, 20, 23, 26, 29, 32,
};

const uint8_t ThreeMenAdjacency[] PROGMEM = {
  1, 3, 4,
  0, 2, 4,
  1, 4, 5,
  0, 4, 6,
  0, 1, 2, 3, 5, 6, 7, 8,
  2, 4, 8,
  3, 4, 7,
  4, 6, 8,
  4, 5, 7,
};

const BoardDefinition ThreeMenBoardDefinition = {
  "three-men",
  "THREE MEN",
  9,
  8,
  ThreeMenBoardPoints,
  ThreeMenMills,
  ThreeMenAdjacencyOffsets,
  ThreeMenAdjacency,
};

const RuleSet ThreeMenRuleSet = {
  "three-men",
  3,
  3,
  0,
  10,
  0,
  RULE_MILL_ACTION_WIN | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardDefinition *const MorrisBoardProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM = {&ClassicBoardDefinition, &FlowerBoardDefinition, &SixMenBoardDefinition, &ThreeMenBoardDefinition};
const RuleSet *const MorrisRuleProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM = {&ClassicRuleSet, &FlowerRuleSet, &SixMenRuleSet, &ThreeMenRuleSet};
