#pragma once

#include "Board.h"
#include "Rules.h"

// Generated by tools/board-data/generate.py. Do not edit by hand.
extern const BoardPoint ClassicBoardPoints[] PROGMEM;
extern const uint8_t ClassicMills[] PROGMEM;
extern const uint8_t ClassicAdjacencyOffsets[] PROGMEM;
extern const uint8_t ClassicAdjacency[] PROGMEM;
extern const BoardDefinition ClassicBoardDefinition;
extern const BoardPoint CrossroadsBoardPoints[] PROGMEM;
extern const uint8_t CrossroadsMills[] PROGMEM;
extern const uint8_t CrossroadsAdjacencyOffsets[] PROGMEM;
extern const uint8_t CrossroadsAdjacency[] PROGMEM;
extern const BoardDefinition CrossroadsBoardDefinition;
extern const BoardPoint FlowerBoardPoints[] PROGMEM;
extern const uint8_t FlowerMills[] PROGMEM;
extern const uint8_t FlowerAdjacencyOffsets[] PROGMEM;
extern const uint8_t FlowerAdjacency[] PROGMEM;
extern const BoardDefinition FlowerBoardDefinition;
extern const BoardPoint FortressBoardPoints[] PROGMEM;
extern const uint8_t FortressMills[] PROGMEM;
extern const uint8_t FortressAdjacencyOffsets[] PROGMEM;
extern const uint8_t FortressAdjacency[] PROGMEM;
extern const BoardDefinition FortressBoardDefinition;
extern const BoardPoint HexTwelveBoardPoints[] PROGMEM;
extern const uint8_t HexTwelveMills[] PROGMEM;
extern const uint8_t HexTwelveAdjacencyOffsets[] PROGMEM;
extern const uint8_t HexTwelveAdjacency[] PROGMEM;
extern const BoardDefinition HexTwelveBoardDefinition;
extern const BoardPoint HourglassBoardPoints[] PROGMEM;
extern const uint8_t HourglassMills[] PROGMEM;
extern const uint8_t HourglassAdjacencyOffsets[] PROGMEM;
extern const uint8_t HourglassAdjacency[] PROGMEM;
extern const BoardDefinition HourglassBoardDefinition;
extern const BoardPoint SixMenBoardPoints[] PROGMEM;
extern const uint8_t SixMenMills[] PROGMEM;
extern const uint8_t SixMenAdjacencyOffsets[] PROGMEM;
extern const uint8_t SixMenAdjacency[] PROGMEM;
extern const BoardDefinition SixMenBoardDefinition;
extern const BoardPoint SpiralBoardPoints[] PROGMEM;
extern const uint8_t SpiralMills[] PROGMEM;
extern const uint8_t SpiralAdjacencyOffsets[] PROGMEM;
extern const uint8_t SpiralAdjacency[] PROGMEM;
extern const BoardDefinition SpiralBoardDefinition;
extern const BoardPoint ThreeMenBoardPoints[] PROGMEM;
extern const uint8_t ThreeMenMills[] PROGMEM;
extern const uint8_t ThreeMenAdjacencyOffsets[] PROGMEM;
extern const uint8_t ThreeMenAdjacency[] PROGMEM;
extern const BoardDefinition ThreeMenBoardDefinition;
extern const RuleSet ClassicRuleSet;
extern const RuleSet CrossroadsRuleSet;
extern const RuleSet FlowerRuleSet;
extern const RuleSet FortressRuleSet;
extern const RuleSet HexTwelveRuleSet;
extern const RuleSet HourglassRuleSet;
extern const RuleSet SixMenRuleSet;
extern const RuleSet SpiralRuleSet;
extern const RuleSet ThreeMenRuleSet;

constexpr uint8_t MORRIS_BOARD_PROFILE_COUNT = 9;
extern const BoardDefinition *const MorrisBoardProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM;
extern const RuleSet *const MorrisRuleProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM;
