#include "GeneratedBoards.h"

// Generated by tools/board-data/generate.py. Do not edit by hand.

const BoardPoint ClassicBoardPoints[] PROGMEM = {
  {4, 4},
  {32, 4},
  {60, 4},
  {12, 12},
  {32, 12},
  {52, 12},
  {20, 20},
  {32, 20},
  {44, 20},
  {4, 32},
  {12, 32},
  {20, 32},
  {44, 32},
  {52, 32},
  {60, 32},
  {20, 44},
  {32, 44},
  {44, 44},
  {12, 52},
  {32, 52},
  {52, 52},
  {4, 60},
  {32, 60},
  {60, 60},
};

const uint8_t ClassicMills[] PROGMEM = {
  0, 1, 2,
  3, 4, 5,
  6, 7, 8,
  9, 10, 11,
  12, 13, 14,
  15, 16, 17,
  18, 19, 20,
  21, 22, 23,
  0, 9, 21,
  3, 10, 18,
  6, 11, 15,
  1, 4, 7,
  16, 19, 22,
  8, 12, 17,
  5, 13, 20,
  2, 14, 23,
};

const uint8_t ClassicAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 9, 13, 15, 17, 20, 22, 25, 29, 32, 35, 39, 42, 44, 47, 49, 51, 55, 57, 59, 62, 64,
};

const uint8_t ClassicAdjacency[] PROGMEM = {
  1, 9,
  0, 2, 4,
  1, 14,
  4, 10,
  1, 3, 5, 7,
  4, 13,
  7, 11,
  4, 6, 8,
  7, 12,
  0, 10, 21,
  3, 9, 11, 18,
  6, 10, 15,
  8, 13, 17,
  5, 12, 14, 20,
  2, 13, 23,
  11, 16,
  15, 17, 19,
  12, 16,
  10, 19,
  16, 18, 20, 22,
  13, 19,
  9, 22,
  19, 21, 23,
  14, 22,
};

const BoardDefinition ClassicBoardDefinition = {
  "CLASSIC 9",
  24,
  16,
  ClassicBoardPoints,
  ClassicMills,
  ClassicAdjacencyOffsets,
  ClassicAdjacency,
};

const RuleSet ClassicRuleSet = {
  9,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint CrossroadsBoardPoints[] PROGMEM = {
  {32, 4},
  {32, 14},
  {20, 20},
  {32, 20},
  {44, 20},
  {4, 32},
  {14, 32},
  {20, 32},
  {32, 32},
  {44, 32},
  {50, 32},
  {60, 32},
  {20, 44},
  {32, 44},
  {44, 44},
  {32, 50},
  {32, 60},
};

const uint8_t CrossroadsMills[] PROGMEM = {
  0, 1, 3,
  2, 3, 4,
  5, 6, 7,
  7, 8, 9,
  9, 10, 11,
  12, 13, 14,
  13, 15, 16,
  2, 7, 12,
  3, 8, 13,
  4, 9, 14,
  2, 8, 14,
  4, 8, 12,
};

const uint8_t CrossroadsAdjacencyOffsets[] PROGMEM = {
  0, 1, 3, 5, 9, 11, 12, 14, 18, 22, 26, 28, 29, 31, 35, 37, 39, 40,
};

const uint8_t CrossroadsAdjacency[] PROGMEM = {
  1,
  0, 3,
  3, 7,
  1, 2, 4, 8,
  3, 9,
  6,
  5, 7,
  2, 6, 8, 12,
  3, 7, 9, 13,
  4, 8, 10, 14,
  9, 11,
  10,
  7, 13,
  8, 12, 14, 15,
  9, 13,
  13, 16,
  15,
};

const BoardDefinition CrossroadsBoardDefinition = {
  "CROSSROADS",
  17,
  12,
  CrossroadsBoardPoints,
  CrossroadsMills,
  CrossroadsAdjacencyOffsets,
  CrossroadsAdjacency,
};

const RuleSet CrossroadsRuleSet = {
  7,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint FlowerBoardPoints[] PROGMEM = {
  {4, 23},
  {4, 35},
  {10, 29},
  {22, 41},
  {29, 35},
  {29, 54},
  {23, 60},
  {35, 60},
  {41, 42},
  {35, 35},
  {54, 35},
  {60, 41},
  {60, 29},
  {42, 23},
  {35, 29},
  {35, 10},
  {41, 4},
  {29, 4},
  {23, 22},
  {29, 29},
};

const uint8_t FlowerMills[] PROGMEM = {
  0, 2, 3,
  5, 4, 19,
  6, 5, 8,
  4, 9, 10,
  11, 10, 13,
  9, 14, 15,
  18, 15, 16,
  2, 19, 14,
};

const uint8_t FlowerAdjacencyOffsets[] PROGMEM = {
  0, 2, 4, 8, 10, 14, 18, 20, 22, 24, 28, 32, 34, 36, 38, 42, 46, 48, 50, 52, 56,
};

const uint8_t FlowerAdjacency[] PROGMEM = {
  1, 2,
  0, 2,
  0, 1, 3, 19,
  2, 4,
  3, 5, 9, 19,
  4, 6, 7, 8,
  5, 7,
  5, 6,
  5, 9,
  4, 8, 10, 14,
  9, 11, 12, 13,
  10, 12,
  10, 11,
  10, 14,
  9, 13, 15, 19,
  14, 16, 17, 18,
  15, 17,
  15, 16,
  15, 19,
  2, 4, 14, 18,
};

const BoardDefinition FlowerBoardDefinition = {
  "FLOWER",
  20,
  8,
  FlowerBoardPoints,
  FlowerMills,
  FlowerAdjacencyOffsets,
  FlowerAdjacency,
};

const RuleSet FlowerRuleSet = {
  7,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint FortressBoardPoints[] PROGMEM = {
  {2, 2},
  {32, 2},
  {62, 2},
  {62, 32},
  {62, 62},
  {32, 62},
  {2, 62},
  {2, 32},
  {32, 8},
  {44, 20},
  {56, 32},
  {44, 44},
  {32, 56},
  {20, 44},
  {8, 32},
  {20, 20},
  {24, 24},
  {32, 24},
  {40, 24},
  {40, 32},
  {40, 40},
  {32, 40},
  {24, 40},
  {24, 32},
};

const uint8_t FortressMills[] PROGMEM = {
  0, 1, 2,
  2, 3, 4,
  4, 5, 6,
  6, 7, 0,
  8, 9, 10,
  10, 11, 12,
  12, 13, 14,
  14, 15, 8,
  16, 17, 18,
  18, 19, 20,
  20, 21, 22,
  22, 23, 16,
  1, 8, 17,
  3, 10, 19,
  5, 12, 21,
  7, 14, 23,
};

const uint8_t FortressAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 10, 12, 15, 17, 20, 24, 26, 30, 32, 36, 38, 42, 44, 46, 49, 51, 54, 56, 59, 61, 64,
};

const uint8_t FortressAdjacency[] PROGMEM = {
  1, 7,
  0, 2, 8,
  1, 3,
  2, 4, 10,
  3, 5,
  4, 6, 12,
  5, 7,
  0, 6, 14,
  1, 9, 15, 17,
  8, 10,
  3, 9, 11, 19,
  10, 12,
  5, 11, 13, 21,
  12, 14,
  7, 13, 15, 23,
  8, 14,
  17, 23,
  8, 16, 18,
  17, 19,
  10, 18, 20,
  19, 21,
  12, 20, 22,
  21, 23,
  14, 16, 22,
};

const BoardDefinition FortressBoardDefinition = {
  "FORTRESS",
  24,
  16,
  FortressBoardPoints,
  FortressMills,
  FortressAdjacencyOffsets,
  FortressAdjacency,
};

const RuleSet FortressRuleSet = {
  9,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint HexTwelveBoardPoints[] PROGMEM = {
  {62, 32},
  {55, 45},
  {47, 58},
  {32, 58},
  {17, 58},
  {10, 45},
  {2, 32},
  {10, 19},
  {17, 6},
  {32, 6},
  {47, 6},
  {55, 19},
  {52, 32},
  {47, 41},
  {42, 49},
  {32, 49},
  {22, 49},
  {17, 41},
  {12, 32},
  {17, 23},
  {22, 15},
  {32, 15},
  {42, 15},
  {47, 23},
  {42, 32},
  {40, 37},
  {37, 41},
  {32, 41},
  {27, 41},
  {24, 37},
  {22, 32},
  {24, 27},
  {27, 23},
  {32, 23},
  {37, 23},
  {40, 27},
};

const uint8_t HexTwelveMills[] PROGMEM = {
  0, 1, 2,
  2, 3, 4,
  4, 5, 6,
  6, 7, 8,
  8, 9, 10,
  10, 11, 0,
  12, 13, 14,
  14, 15, 16,
  16, 17, 18,
  18, 19, 20,
  20, 21, 22,
  22, 23, 12,
  24, 25, 26,
  26, 27, 28,
  28, 29, 30,
  30, 31, 32,
  32, 33, 34,
  34, 35, 24,
  1, 13, 25,
  3, 15, 27,
  5, 17, 29,
  7, 19, 31,
  9, 21, 33,
  11, 23, 35,
};

const uint8_t HexTwelveAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 36, 38, 42, 44, 48, 50, 54, 56, 60, 62, 66, 68, 71, 73, 76, 78, 81, 83, 86, 88, 91, 93, 96,
};

const uint8_t HexTwelveAdjacency[] PROGMEM = {
  1, 11,
  0, 2, 13,
  1, 3,
  2, 4, 15,
  3, 5,
  4, 6, 17,
  5, 7,
  6, 8, 19,
  7, 9,
  8, 10, 21,
  9, 11,
  0, 10, 23,
  13, 23,
  1, 12, 14, 25,
  13, 15,
  3, 14, 16, 27,
  15, 17,
  5, 16, 18, 29,
  17, 19,
  7, 18, 20, 31,
  19, 21,
  9, 20, 22, 33,
  21, 23,
  11, 12, 22, 35,
  25, 35,
  13, 24, 26,
  25, 27,
  15, 26, 28,
  27, 29,
  17, 28, 30,
  29, 31,
  19, 30, 32,
  31, 33,
  21, 32, 34,
  33, 35,
  23, 24, 34,
};

const BoardDefinition HexTwelveBoardDefinition = {
  "HEXAGON",
  36,
  24,
  HexTwelveBoardPoints,
  HexTwelveMills,
  HexTwelveAdjacencyOffsets,
  HexTwelveAdjacency,
};

const RuleSet HexTwelveRuleSet = {
  12,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint HourglassBoardPoints[] PROGMEM = {
  {12, 4},
  {32, 4},
  {52, 4},
  {17, 16},
  {32, 16},
  {47, 16},
  {24, 32},
  {32, 24},
  {40, 32},
  {17, 48},
  {32, 48},
  {47, 48},
  {12, 60},
  {32, 60},
  {52, 60},
  {32, 40},
};

const uint8_t HourglassMills[] PROGMEM = {
  0, 1, 2,
  3, 4, 5,
  9, 10, 11,
  12, 13, 14,
  0, 3, 6,
  6, 9, 12,
  1, 4, 7,
  2, 5, 8,
  8, 11, 14,
  15, 10, 13,
};

const uint8_t HourglassAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 10, 14, 17, 21, 24, 28, 31, 35, 38, 40, 43, 45, 48,
};

const uint8_t HourglassAdjacency[] PROGMEM = {
  1, 3,
  0, 2, 4,
  1, 5,
  0, 4, 6,
  1, 3, 5, 7,
  2, 4, 8,
  3, 7, 9, 15,
  4, 6, 8,
  5, 7, 11, 15,
  6, 10, 12,
  9, 11, 13, 15,
  8, 10, 14,
  9, 13,
  10, 12, 14,
  11, 13,
  6, 8, 10,
};

const BoardDefinition HourglassBoardDefinition = {
  "HOURGLASS",
  16,
  10,
  HourglassBoardPoints,
  HourglassMills,
  HourglassAdjacencyOffsets,
  HourglassAdjacency,
};

const RuleSet HourglassRuleSet = {
  6,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint SixMenBoardPoints[] PROGMEM = {
  {4, 4},
  {32, 4},
  {60, 4},
  {60, 32},
  {60, 60},
  {32, 60},
  {4, 60},
  {4, 32},
  {18, 18},
  {32, 18},
  {46, 18},
  {46, 32},
  {46, 46},
  {32, 46},
  {18, 46},
  {18, 32},
};

const uint8_t SixMenMills[] PROGMEM = {
  0, 1, 2,
  2, 3, 4,
  4, 5, 6,
  6, 7, 0,
  8, 9, 10,
  10, 11, 12,
  12, 13, 14,
  14, 15, 8,
};

const uint8_t SixMenAdjacencyOffsets[] PROGMEM = {
  0, 2, 5, 7, 10, 12, 15, 17, 20, 22, 25, 27, 30, 32, 35, 37, 40,
};

const uint8_t SixMenAdjacency[] PROGMEM = {
  1, 7,
  0, 2, 9,
  1, 3,
  2, 4, 11,
  3, 5,
  4, 6, 13,
  5, 7,
  0, 6, 15,
  9, 15,
  1, 8, 10,
  9, 11,
  3, 10, 12,
  11, 13,
  5, 12, 14,
  13, 15,
  7, 8, 14,
};

const BoardDefinition SixMenBoardDefinition = {
  "SIX MEN",
  16,
  8,
  SixMenBoardPoints,
  SixMenMills,
  SixMenAdjacencyOffsets,
  SixMenAdjacency,
};

const RuleSet SixMenRuleSet = {
  6,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint SpiralBoardPoints[] PROGMEM = {
  {8, 8},
  {20, 8},
  {32, 8},
  {44, 8},
  {56, 8},
  {56, 20},
  {56, 32},
  {56, 44},
  {56, 56},
  {44, 56},
  {32, 56},
  {20, 56},
  {8, 56},
  {8, 44},
  {8, 32},
  {8, 20},
  {20, 20},
  {32, 20},
  {44, 20},
  {44, 32},
  {44, 44},
  {32, 44},
  {20, 44},
  {20, 32},
  {32, 32},
};

const uint8_t SpiralMills[] PROGMEM = {
  0, 1, 2,
  2, 3, 4,
  4, 5, 6,
  6, 7, 8,
  8, 9, 10,
  10, 11, 12,
  12, 13, 14,
  14, 15, 0,
  16, 17, 18,
  18, 19, 20,
  20, 21, 22,
  22, 23, 16,
  17, 24, 21,
  23, 24, 19,
};

const uint8_t SpiralAdjacencyOffsets[] PROGMEM = {
  0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 33, 36, 39, 41, 44, 46, 49, 51, 54, 58,
};

const uint8_t SpiralAdjacency[] PROGMEM = {
  1, 15,
  0, 2,
  1, 3,
  2, 4,
  3, 5,
  4, 6,
  5, 7,
  6, 8,
  7, 9,
  8, 10,
  9, 11,
  10, 12,
  11, 13,
  12, 14,
  13, 15,
  0, 14, 16,
  15, 17, 23,
  16, 18, 24,
  17, 19,
  18, 20, 24,
  19, 21,
  20, 22, 24,
  21, 23,
  16, 22, 24,
  17, 19, 21, 23,
};

const BoardDefinition SpiralBoardDefinition = {
  "SPIRAL",
  25,
  14,
  SpiralBoardPoints,
  SpiralMills,
  SpiralAdjacencyOffsets,
  SpiralAdjacency,
};

const RuleSet SpiralRuleSet = {
  9,
  3,
  3,
  50,
  0,
  RULE_FLYING_ENABLED | RULE_PROTECT_PIECES_IN_MILLS | RULE_BLOCK_WIN_ENABLED | RULE_MATERIAL_WIN_ENABLED | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardPoint ThreeMenBoardPoints[] PROGMEM = {
  {12, 12},
  {32, 12},
  {52, 12},
  {12, 32},
  {32, 32},
  {52, 32},
  {12, 52},
  {32, 52},
  {52, 52},
};

const uint8_t ThreeMenMills[] PROGMEM = {
  0, 1, 2,
  3, 4, 5,
  6, 7, 8,
  0, 3, 6,
  1, 4, 7,
  2, 5, 8,
  0, 4, 8,
  2, 4, 6,
};

const uint8_t ThreeMenAdjacencyOffsets[] PROGMEM = {
  0, 3, 6, 9, 12, 20, 23, 26, 29, 32,
};

const uint8_t ThreeMenAdjacency[] PROGMEM = {
  1, 3, 4,
  0, 2, 4,
  1, 4, 5,
  0, 4, 6,
  0, 1, 2, 3, 5, 6, 7, 8,
  2, 4, 8,
  3, 4, 7,
  4, 6, 8,
  4, 5, 7,
};

const BoardDefinition ThreeMenBoardDefinition = {
  "THREE MEN",
  9,
  8,
  ThreeMenBoardPoints,
  ThreeMenMills,
  ThreeMenAdjacencyOffsets,
  ThreeMenAdjacency,
};

const RuleSet ThreeMenRuleSet = {
  3,
  3,
  0,
  10,
  0,
  RULE_MILL_ACTION_WIN | RULE_BLOCK_WIN_REQUIRES_RESERVE_EMPTY | RULE_MATERIAL_WIN_REQUIRES_RESERVE_EMPTY,
};

const BoardDefinition *const MorrisBoardProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM = {&ClassicBoardDefinition, &CrossroadsBoardDefinition, &FlowerBoardDefinition, &FortressBoardDefinition, &HexTwelveBoardDefinition, &HourglassBoardDefinition, &SixMenBoardDefinition, &SpiralBoardDefinition, &ThreeMenBoardDefinition};
const RuleSet *const MorrisRuleProfiles[MORRIS_BOARD_PROFILE_COUNT] PROGMEM = {&ClassicRuleSet, &CrossroadsRuleSet, &FlowerRuleSet, &FortressRuleSet, &HexTwelveRuleSet, &HourglassRuleSet, &SixMenRuleSet, &SpiralRuleSet, &ThreeMenRuleSet};
